"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,BarChart3,CalendarDays,ChevronRight,CircleDollarSign,ClipboardList,FileCheck2,FileText,Gauge,LayoutDashboard,Menu,Pencil,Plus,Search,UploadCloud,Users,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Progress} from "@/components/ui/progress";
type P={id:string;name:string;code:string;objective:string;status:string;health:string;progress:number;budget:number;spent:number;start_date:string;end_date:string};
type T={id:string;project_id:string;title:string;assignee:string;due_date:string;status:string;priority:string;critical:number;depends_on:string|null};
type D={projects:P[];tasks:T[];meetings:any[];metrics:any[]};
const nav=[["Portfolio",LayoutDashboard],["Projects",Gauge],["Schedule",CalendarDays],["Tasks",ClipboardList],["Budgets",CircleDollarSign],["Meetings",Users],["Metrics",BarChart3],["Reports",FileText]] as const;
const usd=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const dt=(s:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(s+"T12:00:00Z"));
const hl=(s:string)=>s==="good"?"On track":s==="watch"?"Watch":"At risk";
async function extractFileText(file:File){
 const ext=file.name.split(".").pop()?.toLowerCase()??"",bytes=new Uint8Array(await file.arrayBuffer());
 if(ext==="txt"||ext==="md"||ext==="csv")return new TextDecoder().decode(bytes);
 if(ext==="docx"){const mammoth=(await import("mammoth")).default;return (await mammoth.extractRawText({arrayBuffer:bytes.buffer})).value}
 if(ext==="pdf"){const {extractText}=await import("unpdf");const result=await extractText(bytes,{mergePages:true});return String(result.text)}
 if(ext==="xlsx"||ext==="xls"){const XLSX=await import("xlsx");const book=XLSX.read(bytes,{type:"array"});return book.SheetNames.map(name=>"# "+name+"\n"+XLSX.utils.sheet_to_csv(book.Sheets[name])).join("\n\n")}
 return "";
}
export default function ProjectControl({displayName}:{displayName:string}){
 const[d,setD]=useState<D|null>(null),[view,setView]=useState("Portfolio"),[pick,setPick]=useState<P|null>(null),[add,setAdd]=useState(false),[newProject,setNewProject]=useState(false),[importProject,setImportProject]=useState(false),[mobile,setMobile]=useState(false),[search,setSearch]=useState("");
 const load=()=>fetch("/api/workspace").then(r=>r.json()).then(setD);useEffect(()=>{void load()},[]);
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const a=new AbortController();c.registerTool({name:"list_portfolio_risks",description:"List at-risk projects and blocked critical tasks.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({projects:d?.projects.filter(p=>p.health==="risk")||[],tasks:d?.tasks.filter(t=>t.critical&&t.status==="Blocked")||[]})},{signal:a.signal});return()=>a.abort()},[d]);
 const total=useMemo(()=>d?{b:d.projects.reduce((s,p)=>s+p.budget,0),s:d.projects.reduce((s,p)=>s+p.spent,0)}:null,[d]);
 if(!d||!total)return <div className="loading"><b>PC</b><span>Loading project control…</span></div>;
 if(!d.projects.length){if(importProject)return <ProjectWizard displayName={displayName} saved={load} cancel={()=>setImportProject(false)}/>;return <EmptyWorkspace displayName={displayName} manual={()=>setNewProject(true)} imported={()=>setImportProject(true)} modal={newProject?<ProjectForm close={()=>setNewProject(false)} saved={load}/>:null}/>}
 return <div className="shell"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><b>PC</b><span><strong>Project Control</strong><small>Engineering portfolio</small></span></div><nav>{nav.map(([n,I])=><button key={n} className={view===n?"active":""} onClick={()=>{setView(n);setMobile(false)}}><I/>{n}</button>)}</nav><div className="live">● Persistent sync enabled</div></aside>
 <main><header><button className="menubtn" onClick={()=>setMobile(!mobile)}><Menu/></button><div><small>{view}</small><h1>{view==="Portfolio"?"Good afternoon, "+displayName.split(" ")[0]:view}</h1></div><div className="actions"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks"/></label><Button onClick={()=>setAdd(true)}><Plus/>Add task</Button></div></header>
 <div className="content">{view==="Portfolio"&&<Portfolio d={d} b={total.b} s={total.s} pick={setPick}/>}
 {view==="Projects"&&<Projects d={d} pick={setPick} add={()=>setNewProject(true)}/>} {view==="Schedule"&&<Schedule d={d}/>}
 {view==="Tasks"&&<Tasks d={d} q={search} reload={load}/>} {view==="Budgets"&&<Budgets d={d} reload={load}/>}
 {view==="Meetings"&&<Meetings d={d} reload={load}/>} {view==="Metrics"&&<Metrics d={d} reload={load}/>} {view==="Reports"&&<Reports d={d}/>}</div></main>
 {mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>} {pick&&<Drawer p={pick} tasks={d.tasks.filter(t=>t.project_id===pick.id)} close={()=>setPick(null)} saved={()=>{setPick(null);void load()}}/>} {add&&<Add projects={d.projects} tasks={d.tasks} close={()=>setAdd(false)} saved={()=>{setAdd(false);void load()}}/>}{newProject&&<ProjectForm close={()=>setNewProject(false)} saved={()=>{setNewProject(false);void load()}}/>}</div>
}
function EmptyWorkspace({displayName,manual,imported,modal}:{displayName:string;manual:()=>void;imported:()=>void;modal:React.ReactNode}){return <main className="onboarding"><header><div className="brand light"><b>PC</b><span><strong>Project Control</strong><small>Engineering portfolio</small></span></div><small>Signed in as {displayName}</small></header><section className="start"><small>YOUR WORKSPACE</small><h1>Add your first project</h1><p>Enter the project directly, or optionally use documents to suggest initial charter information. Nothing in the workspace depends on document import.</p><div><button onClick={manual}><Pencil/><strong>Enter project manually</strong><span>Start with a short, editable project form</span></button><button onClick={imported}><UploadCloud/><strong>Start from documents</strong><span>Import files and review suggested values</span></button></div></section>{modal}</main>}
function ProjectWizard({displayName,saved,cancel}:{displayName:string;saved:()=>void;cancel:()=>void}){
 const[step,setStep]=useState(1),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[files,setFiles]=useState<File[]>([]),[docs,setDocs]=useState<{filename:string;size:number}[]>([]),[error,setError]=useState("");
 const[draftId]=useState(()=>Date.now().toString(36)+"-"+Math.random().toString(36).slice(2)),[form,setForm]=useState({name:"",code:"",kind:"Development",objective:"",success:"",startDate:"",endDate:"",budget:""});
 const update=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 const importDocs=async()=>{
  if(!files.length){setStep(2);return} setUploading(true);setError("");
  try{
  const encoded=await Promise.all(files.map(async file=>{const bytes=new Uint8Array(await file.arrayBuffer());let data="";for(let i=0;i<bytes.length;i+=32768)data+=String.fromCharCode(...bytes.subarray(i,i+32768));return{name:file.name,type:file.type,size:file.size,data:btoa(data),text:(await extractFileText(file)).slice(0,120000)}}));
  const response=await fetch("/api/documents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({draftId,files:encoded})}),result=await response.json();
  if(!response.ok){setError(result.error||"Document import failed");setUploading(false);return}
  setDocs(result.uploaded);setForm(current=>{const next={...current};for(const[key,value]of Object.entries(result.suggestions as Record<string,string>))if(value&&!next[key as keyof typeof next])next[key as keyof typeof next]=value;return next});setUploading(false);setStep(2);
  }catch{setError("Document import failed. Please try again or continue without importing.");setUploading(false)}
 };
 const next=(e:React.FormEvent)=>{e.preventDefault();setStep(s=>Math.min(5,s+1))};
 const create=async()=>{setBusy(true);const objective=form.success?form.objective+" Success looks like: "+form.success:form.objective;await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"project",...form,objective,draftId})});saved()};
 return <main className="onboarding"><header><div className="brand light"><b>PC</b><span><strong>Project Control</strong><small>Engineering portfolio</small></span></div><Button variant="outline" onClick={cancel}>Cancel import</Button></header><section className="wizard"><div className="wizardintro"><small>DOCUMENT-ASSISTED SETUP</small><h1>Create a project from source files</h1><p>Import is optional. Suggestions are editable and can be replaced with your own project information.</p></div><div className="steps">{["Documents","Project","Objectives","Plan","Review"].map((label,i)=><div className={step===i+1?"current":step>i+1?"done":""} key={label}><b>{step>i+1?"✓":i+1}</b><span>{label}</span></div>)}</div>
 {step===1?<section className="uploadstep"><h2>Import project documents <small>Optional</small></h2><p>Upload up to five source files. We’ll retain them with the project and suggest values for the charter.</p><label className="dropzone"><UploadCloud/><strong>Choose project documents</strong><span>PDF, Word, Excel, CSV, text, or Markdown · 10 MB each</span><input type="file" multiple accept=".pdf,.docx,.xlsx,.xls,.csv,.txt,.md" onChange={e=>setFiles(Array.from(e.target.files??[]).slice(0,5))}/></label>{files.length>0&&<div className="filelist">{files.map(file=><div key={file.name}><FileText/><span><strong>{file.name}</strong><small>{(file.size/1024).toFixed(0)} KB</small></span></div>)}</div>}{error&&<p className="uploaderror">{error}</p>}<footer><Button variant="outline" onClick={()=>setStep(2)}>Skip for now</Button><Button disabled={uploading} onClick={()=>void importDocs()}>{uploading?"Reading documents…":"Import and continue"}</Button></footer></section>:
 <form onSubmit={next}>
  {step===2&&<fieldset><legend>Project identity</legend><p>{docs.length?docs.length+" document"+(docs.length===1?"":"s")+" imported. Review the suggested values below.":"Give the project a recognizable name and short code."}</p>{docs.length>0&&<div className="imported"><FileCheck2/><span>Suggestions imported from {docs.map(d=>d.filename).join(", ")}</span></div>}<label>Project name<input required value={form.name} onChange={e=>update("name",e.target.value)} placeholder="e.g., Regional Sensor Upgrade"/></label><div><label>Project code<input required value={form.code} onChange={e=>update("code",e.target.value)} placeholder="RSU-01"/></label><label>Project type<select value={form.kind} onChange={e=>update("kind",e.target.value)}><option>Development</option><option>Operations</option><option>Research</option><option>Infrastructure</option></select></label></div></fieldset>}
  {step===3&&<fieldset><legend>Purpose and outcomes</legend><p>Confirm the extracted purpose and how you will recognize success.</p><label>Primary objective<textarea required value={form.objective} onChange={e=>update("objective",e.target.value)} placeholder="What problem are we solving, and what outcome must the project deliver?"/></label><label>Success criteria<textarea value={form.success} onChange={e=>update("success",e.target.value)} placeholder="Measurable technical, schedule, or operational outcomes"/></label></fieldset>}
  {step===4&&<fieldset><legend>Initial plan</legend><p>Confirm the suggested schedule and budget baseline.</p><div><label>Start date<input type="date" required value={form.startDate} onChange={e=>update("startDate",e.target.value)}/></label><label>Target completion<input type="date" required min={form.startDate} value={form.endDate} onChange={e=>update("endDate",e.target.value)}/></label></div><label>Authorized budget (USD)<input type="number" min="0" step="1000" value={form.budget} onChange={e=>update("budget",e.target.value)} placeholder="0"/></label></fieldset>}
  {step===5&&<fieldset><legend>Review project charter</legend><p>Confirm the initial baseline. Every field can be refined after creation.</p><dl><div><dt>Project</dt><dd>{form.name} <small>{form.code.toUpperCase()}</small></dd></div><div><dt>Type</dt><dd>{form.kind}</dd></div><div><dt>Objective</dt><dd>{form.objective}</dd></div><div><dt>Schedule</dt><dd>{form.startDate} to {form.endDate}</dd></div><div><dt>Budget</dt><dd>{usd(Number(form.budget)||0)}</dd></div><div><dt>Documents</dt><dd>{docs.length?docs.map(d=>d.filename).join(", "):"None"}</dd></div></dl></fieldset>}
  <footer><Button type="button" variant="outline" onClick={()=>setStep(s=>s-1)}>Back</Button>{step<5?<Button type="submit">Continue</Button>:<Button type="button" disabled={busy} onClick={()=>void create()}>{busy?"Creating project…":"Create project"}</Button>}</footer>
 </form>}</section></main>
}
const Head=({t,s}:{t:string;s:string})=><div className="phead"><h2>{t}</h2><p>{s}</p></div>;
function Portfolio({d,b,s,pick}:{d:D;b:number;s:number;pick:(p:P)=>void}){const avg=Math.round(d.projects.reduce((a,p)=>a+p.progress,0)/d.projects.length),used=b?Math.round(s/b*100):0;return <><section className="stats"><Stat l="Active projects" v={String(d.projects.length)} s="Across development and operations" c="blue"/><Stat l="Portfolio progress" v={avg+"%"} s="Schedule completion" c="teal"/><Stat l="Budget used" v={used+"%"} s={usd(b-s)+" remaining"} c="gold"/><Stat l="Blocked tasks" v={String(d.tasks.filter(t=>t.status==="Blocked").length)} s={d.tasks.filter(t=>t.critical).length+" critical-path tasks"} c="red"/></section><div className="grid"><section className="panel"><Head t="Portfolio health" s="Select a project to drill down"/><div className="plist">{d.projects.map(p=><button key={p.id} onClick={()=>pick(p)}><i className={p.health}/><span><strong>{p.name}</strong><small>{p.code} · {p.status}</small></span><span><b>{p.progress}%</b><Progress value={p.progress}/></span><span><strong>{usd(p.spent)}</strong><small>of {usd(p.budget)}</small></span><em className={p.health}>{hl(p.health)}</em><ChevronRight/></button>)}</div></section><section className="panel"><Head t="Needs attention" s="Critical and blocked work"/><div className="attention">{d.tasks.filter(t=>t.critical).slice(0,4).map(t=><div key={t.id}><AlertTriangle/><span><strong>{t.title}</strong><small>Due {dt(t.due_date)} · {t.assignee}</small></span><em className={t.status==="Blocked"?"risk":"watch"}>{t.status}</em></div>)}</div></section></div><div className="grid lower"><section className="panel"><Head t="Critical path — next 30 days" s="Dependency-aware milestones"/><div className="timeline">{d.tasks.filter(t=>t.critical).map((t,i)=><div key={t.id}><b>{i+1}</b><span><strong>{t.title}</strong><small>{t.assignee} · {dt(t.due_date)}</small></span></div>)}</div></section><section className="panel"><Head t="Budget position" s="Committed spending by project"/>{d.projects.map(p=>{const value=p.budget?p.spent/p.budget*100:0;return <div className="bar" key={p.id}><span><b>{p.code}</b><b>{Math.round(value)}%</b></span><Progress value={value}/></div>})}</section></div></>}
const Stat=({l,v,s,c}:{l:string;v:string;s:string;c:string})=><article className={"stat "+c}><span>{l}</span><strong>{v}</strong><small>{s}</small></article>;
function Projects({d,pick,add}:{d:D;pick:(p:P)=>void;add:()=>void}){return <><div className="viewbar"><Head t="Projects" s="Open a project to update its baseline and status"/><Button onClick={add}><Plus/>New project</Button></div><div className="cards">{d.projects.map(p=><button className="pcard" key={p.id} onClick={()=>pick(p)}><span><em className={p.health}>{hl(p.health)}</em><small>{p.code}</small></span><h2>{p.name}</h2><p>{p.objective}</p><Progress value={p.progress}/><small>{p.progress}% complete · {usd(p.budget-p.spent)} remaining</small></button>)}</div></>}
function Schedule({d}:{d:D}){const dates=d.tasks.map(t=>Date.parse(t.due_date+"T12:00:00Z")),lo=Math.min(...dates),hi=Math.max(...dates),range=Math.max(1,hi-lo);return <section className="panel"><Head t="Integrated schedule" s="Due dates are positioned across the current task range; critical path is red"/>{!d.tasks.length&&<Empty text="Add tasks to build the integrated schedule."/>}<div className="gantt">{d.tasks.map(t=><div key={t.id}><span className="tasklabel"><strong>{t.title}</strong>{t.depends_on&&<small>Depends on {d.tasks.find(x=>x.id===t.depends_on)?.title}</small>}</span><span><i className={t.critical?"critical":""} style={{left:Math.min(92,Math.max(1,(Date.parse(t.due_date+"T12:00:00Z")-lo)/range*92))+"%"}}/></span><small>{dt(t.due_date)}</small></div>)}</div></section>}
function Tasks({d,q,reload}:{d:D;q:string;reload:()=>void}){const a=d.tasks.filter(t=>(t.title+t.assignee+t.status).toLowerCase().includes(q.toLowerCase()));const toggle=async(t:T)=>{await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"task-status",id:t.id,status:t.status==="Complete"?"Not started":"Complete"})});reload()};return <section className="panel"><Head t="Task register" s={a.length+" matching tasks"}/><div className="table"><div className="tr th"><span>Task</span><span>Project</span><span>Owner</span><span>Due</span><span>Status</span></div>{a.map(t=><button className="tr" key={t.id} onClick={()=>void toggle(t)}><span>{t.critical&&<i/>}{t.title}</span><span>{d.projects.find(p=>p.id===t.project_id)?.code}</span><span>{t.assignee}</span><span>{dt(t.due_date)}</span><em className={t.status==="Blocked"?"risk":""}>{t.status}</em></button>)}</div></section>}
function Budgets({d,reload}:{d:D;reload:()=>void}){const[edit,setEdit]=useState<P|null>(null);return <><section className="panel"><Head t="Budget control" s="Authorized budget versus current spending"/><div className="budgets">{d.projects.map(p=><button key={p.id} onClick={()=>setEdit(p)}><span><strong>{p.name}</strong><b>{usd(p.spent)} / {usd(p.budget)}</b></span><Progress value={p.budget?Math.min(100,p.spent/p.budget*100):0}/><small>{usd(p.budget-p.spent)} available · select to update</small></button>)}</div></section>{edit&&<BudgetForm project={edit} close={()=>setEdit(null)} saved={()=>{setEdit(null);reload()}}/>}</>}
function Meetings({d,reload}:{d:D;reload:()=>void}){const[open,setOpen]=useState(false);return <><section className="panel"><div className="viewbar"><Head t="Meeting center" s="Agendas, decisions, and notes"/><Button onClick={()=>setOpen(true)}><Plus/>New meeting</Button></div>{!d.meetings.length&&<Empty text="No meetings recorded yet."/>}{d.meetings.map(m=><article className="meeting" key={m.id}><b>{new Date(m.meeting_date+"T12:00:00Z").getUTCDate()}<small>{new Date(m.meeting_date+"T12:00:00Z").toLocaleString("en-US",{month:"short",timeZone:"UTC"}).toUpperCase()}</small></b><div><small>{d.projects.find(p=>p.id===m.project_id)?.name}</small><h2>{m.title}</h2><p><strong>Agenda:</strong> {m.agenda||"Not entered"}</p>{m.notes&&<p><strong>Notes:</strong> {m.notes}</p>}</div></article>)}</section>{open&&<MeetingForm projects={d.projects} close={()=>setOpen(false)} saved={()=>{setOpen(false);reload()}}/>}</>}
function Metrics({d,reload}:{d:D;reload:()=>void}){const[open,setOpen]=useState(false);return <><section className="panel"><div className="viewbar"><Head t="Operational metrics" s="Latest performance against target"/><Button onClick={()=>setOpen(true)}><Plus/>Record metric</Button></div>{!d.metrics.length&&<Empty text="No metrics recorded yet."/>}<div className="metricgrid">{d.metrics.map(m=><div key={m.id}><Gauge/><small>{d.projects.find(p=>p.id===m.project_id)?.code} · {m.name}</small><strong>{m.value}{m.unit}</strong><span>Target {m.target}{m.unit}</span><Progress value={m.target?Math.min(100,m.value/m.target*100):0}/></div>)}</div></section>{open&&<MetricForm projects={d.projects} close={()=>setOpen(false)} saved={()=>{setOpen(false);reload()}}/>}</>}
function Reports({d}:{d:D}){return <section className="panel report"><Head t="Portfolio status report" s="Generated from current project records"/><div className="reporthead"><span><small>Reporting period</small><strong>September 2026</strong></span><Button onClick={()=>window.print()}><FileText/>Print / save PDF</Button></div><h2>Executive summary</h2><p>{d.projects.length} active programs are tracked. {d.projects.filter(p=>p.health==="good").length} are on track and {d.projects.filter(p=>p.health==="risk").length} require management attention. Spending is {usd(d.projects.reduce((s,p)=>s+p.spent,0))} against {usd(d.projects.reduce((s,p)=>s+p.budget,0))} authorized.</p><h2>Priority actions</h2><ul>{d.tasks.filter(t=>t.critical).map(t=><li key={t.id}>{t.title} — {t.status}, due {dt(t.due_date)}</li>)}</ul></section>}
function Drawer({p,tasks,close,saved}:{p:P;tasks:T[];close:()=>void;saved:()=>void}){const[editing,setEditing]=useState(false);if(editing)return <ProjectForm project={p} close={()=>setEditing(false)} saved={saved}/>;return <div className="overlay"><button onClick={close}/><aside className="drawer"><button className="close" onClick={close}><X/></button><em className={p.health}>{hl(p.health)}</em><small>{p.code}</small><h2>{p.name}</h2><p>{p.objective}</p><Button variant="outline" onClick={()=>setEditing(true)}><Pencil/>Edit project</Button><div className="kpis"><span><small>Progress</small><strong>{p.progress}%</strong></span><span><small>Budget remaining</small><strong>{usd(p.budget-p.spent)}</strong></span></div><h3>Open work</h3>{tasks.map(t=><div className="dtask" key={t.id}><ClipboardList/><span><strong>{t.title}</strong><small>{t.assignee} · {t.status}</small></span></div>)}</aside></div>}
function Add({projects,tasks,close,saved}:{projects:P[];tasks:T[];close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:"task",title:f.get("title"),projectId:f.get("project"),assignee:f.get("assignee"),dueDate:f.get("due"),priority:f.get("priority"),critical:f.get("critical")==="on",dependsOn:f.get("dependsOn")});saved()};return <Modal title="Add task" close={close} submit={submit} busy={busy}><label>Task title<input name="title" required autoFocus/></label><label>Project<select name="project">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div><label>Assignee<input name="assignee" required/></label><label>Due date<input type="date" name="due" required/></label></div><div><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label><label>Depends on<select name="dependsOn"><option value="">No dependency</option>{tasks.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label></div><label className="check"><input type="checkbox" name="critical"/>Critical-path task</label></Modal>}
const post=(body:Record<string,unknown>)=>fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
const today=()=>new Date().toISOString().slice(0,10);
function Empty({text}:{text:string}){return <div className="empty"><FileText/><p>{text}</p></div>}
function Modal({title,close,submit,busy,children}:{title:string;close:()=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean;children:React.ReactNode}){return <div className="overlay modalwrap"><button onClick={close}/><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={close}><X/></button><h2>{title}</h2>{children}<footer><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?"Saving…":"Save"}</Button></footer></form></div>}
function ProjectForm({project,close,saved}:{project?:P;close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:project?"project-update":"project",id:project?.id,name:f.get("name"),code:f.get("code"),objective:f.get("objective"),status:f.get("status")||"Planning",health:f.get("health")||"good",progress:f.get("progress")||0,budget:f.get("budget"),spent:f.get("spent")||0,startDate:f.get("startDate"),endDate:f.get("endDate"),draftId:""});saved()};return <Modal title={project?"Edit project":"New project"} close={close} submit={submit} busy={busy}><div><label>Project name<input name="name" required autoFocus defaultValue={project?.name}/></label><label>Project code<input name="code" required defaultValue={project?.code}/></label></div><label>Primary objective<textarea name="objective" required defaultValue={project?.objective}/></label>{project&&<div><label>Status<select name="status" defaultValue={project.status}><option>Planning</option><option>Active</option><option>On hold</option><option>Complete</option></select></label><label>Health<select name="health" defaultValue={project.health}><option value="good">On track</option><option value="watch">Watch</option><option value="risk">At risk</option></select></label></div>}<div><label>Start date<input type="date" name="startDate" required defaultValue={project?.start_date||today()}/></label><label>Target completion<input type="date" name="endDate" required defaultValue={project?.end_date||today()}/></label></div><div><label>Authorized budget<input type="number" min="0" step="100" name="budget" defaultValue={project?.budget||0}/></label>{project&&<label>Spent to date<input type="number" min="0" step="100" name="spent" defaultValue={project.spent}/></label>}</div>{project&&<label>Progress ({project.progress}%)<input type="range" name="progress" min="0" max="100" defaultValue={project.progress}/></label>}</Modal>}
function BudgetForm({project,close,saved}:{project:P;close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:"project-update",id:project.id,name:project.name,code:project.code,objective:project.objective,status:project.status,health:project.health,progress:project.progress,budget:f.get("budget"),spent:f.get("spent"),startDate:project.start_date,endDate:project.end_date});saved()};return <Modal title={"Update budget — "+project.code} close={close} submit={submit} busy={busy}><div><label>Authorized budget<input name="budget" type="number" min="0" step="100" defaultValue={project.budget}/></label><label>Spent to date<input name="spent" type="number" min="0" step="100" defaultValue={project.spent}/></label></div></Modal>}
function MeetingForm({projects,close,saved}:{projects:P[];close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:"meeting",projectId:f.get("project"),title:f.get("title"),meetingDate:f.get("date"),agenda:f.get("agenda"),notes:f.get("notes")});saved()};return <Modal title="New meeting record" close={close} submit={submit} busy={busy}><label>Project<select name="project">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div><label>Meeting title<input name="title" required/></label><label>Date<input name="date" type="date" required defaultValue={today()}/></label></div><label>Agenda<textarea name="agenda" placeholder="Topics and desired decisions"/></label><label>Notes and decisions<textarea name="notes" placeholder="Decisions, actions, and follow-ups"/></label></Modal>}
function MetricForm({projects,close,saved}:{projects:P[];close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:"metric",projectId:f.get("project"),name:f.get("name"),value:f.get("value"),target:f.get("target"),unit:f.get("unit"),measuredAt:f.get("date")});saved()};return <Modal title="Record project metric" close={close} submit={submit} busy={busy}><label>Project<select name="project">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Metric name<input name="name" required placeholder="e.g., System availability"/></label><div><label>Current value<input name="value" type="number" step="any" required/></label><label>Target<input name="target" type="number" step="any" required/></label></div><div><label>Unit<input name="unit" placeholder="%, days, units"/></label><label>Measured on<input name="date" type="date" required defaultValue={today()}/></label></div></Modal>}
