"use client";
import {useEffect,useMemo,useState} from "react";
import {AlertTriangle,BarChart3,CalendarDays,ChevronRight,CircleDollarSign,ClipboardList,FileText,Gauge,LayoutDashboard,Menu,Plus,Search,Users,X} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Progress} from "@/components/ui/progress";
type P={id:string;name:string;code:string;objective:string;status:string;health:string;progress:number;budget:number;spent:number;start_date:string;end_date:string};
type T={id:string;project_id:string;title:string;assignee:string;due_date:string;status:string;priority:string;critical:number;depends_on:string|null};
type D={projects:P[];tasks:T[];meetings:any[];metrics:any[]};
const nav=[["Portfolio",LayoutDashboard],["Projects",Gauge],["Schedule",CalendarDays],["Tasks",ClipboardList],["Budgets",CircleDollarSign],["Meetings",Users],["Metrics",BarChart3],["Reports",FileText]] as const;
const usd=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const dt=(s:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric"}).format(new Date(s+"T12:00:00Z"));
const hl=(s:string)=>s==="good"?"On track":s==="watch"?"Watch":"At risk";
export default function ProjectControl({displayName}:{displayName:string}){
 const[d,setD]=useState<D|null>(null),[view,setView]=useState("Portfolio"),[pick,setPick]=useState<P|null>(null),[add,setAdd]=useState(false),[mobile,setMobile]=useState(false),[search,setSearch]=useState("");
 const load=()=>fetch("/api/workspace").then(r=>r.json()).then(setD);useEffect(()=>{void load()},[]);
 useEffect(()=>{const c=(document as any).modelContext;if(!c?.registerTool)return;const a=new AbortController();c.registerTool({name:"list_portfolio_risks",description:"List at-risk projects and blocked critical tasks.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({projects:d?.projects.filter(p=>p.health==="risk")||[],tasks:d?.tasks.filter(t=>t.critical&&t.status==="Blocked")||[]})},{signal:a.signal});return()=>a.abort()},[d]);
 const total=useMemo(()=>d?{b:d.projects.reduce((s,p)=>s+p.budget,0),s:d.projects.reduce((s,p)=>s+p.spent,0)}:null,[d]);
 if(!d||!total)return <div className="loading"><b>PC</b><span>Loading project control…</span></div>;
 if(!d.projects.length)return <ProjectWizard displayName={displayName} saved={load}/>;
 return <div className="shell"><aside className={mobile?"sidebar open":"sidebar"}><div className="brand"><b>PC</b><span><strong>Project Control</strong><small>Engineering portfolio</small></span></div><nav>{nav.map(([n,I])=><button key={n} className={view===n?"active":""} onClick={()=>{setView(n);setMobile(false)}}><I/>{n}</button>)}</nav><div className="live">● Persistent sync enabled</div></aside>
 <main><header><button className="menubtn" onClick={()=>setMobile(!mobile)}><Menu/></button><div><small>{view}</small><h1>{view==="Portfolio"?"Good afternoon, "+displayName.split(" ")[0]:view}</h1></div><div className="actions"><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search tasks"/></label><Button onClick={()=>setAdd(true)}><Plus/>Add task</Button></div></header>
 <div className="content">{view==="Portfolio"&&<Portfolio d={d} b={total.b} s={total.s} pick={setPick}/>}
 {view==="Projects"&&<Projects d={d} pick={setPick}/>} {view==="Schedule"&&<Schedule d={d}/>}
 {view==="Tasks"&&<Tasks d={d} q={search} reload={load}/>} {view==="Budgets"&&<Budgets d={d}/>}
 {view==="Meetings"&&<Meetings d={d}/>} {view==="Metrics"&&<Metrics d={d}/>} {view==="Reports"&&<Reports d={d}/>}</div></main>
 {mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>} {pick&&<Drawer p={pick} tasks={d.tasks.filter(t=>t.project_id===pick.id)} close={()=>setPick(null)}/>} {add&&<Add projects={d.projects} close={()=>setAdd(false)} saved={()=>{setAdd(false);void load()}}/>}</div>
}
function ProjectWizard({displayName,saved}:{displayName:string;saved:()=>void}){
 const[step,setStep]=useState(1),[busy,setBusy]=useState(false),[form,setForm]=useState({name:"",code:"",kind:"Development",objective:"",success:"",startDate:"",endDate:"",budget:""});
 const update=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 const next=(e:React.FormEvent)=>{e.preventDefault();setStep(s=>Math.min(4,s+1))};
 const create=async()=>{setBusy(true);const objective=form.success?form.objective+" Success looks like: "+form.success:form.objective;await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"project",...form,objective})});saved()};
 return <main className="onboarding"><header><div className="brand light"><b>PC</b><span><strong>Project Control</strong><small>Engineering portfolio</small></span></div><small>Signed in as {displayName}</small></header><section className="wizard"><div className="wizardintro"><small>NEW WORKSPACE</small><h1>Create your first project</h1><p>We’ll establish the project charter, schedule, and initial budget. You can add workstreams, tasks, metrics, and meetings afterward.</p></div><div className="steps">{["Project","Objectives","Plan","Review"].map((label,i)=><div className={step===i+1?"current":step>i+1?"done":""} key={label}><b>{step>i+1?"✓":i+1}</b><span>{label}</span></div>)}</div>
 <form onSubmit={next}>
  {step===1&&<fieldset><legend>Project identity</legend><p>Give the project a recognizable name and short code.</p><label>Project name<input required value={form.name} onChange={e=>update("name",e.target.value)} placeholder="e.g., Regional Sensor Upgrade"/></label><div><label>Project code<input required value={form.code} onChange={e=>update("code",e.target.value)} placeholder="RSU-01"/></label><label>Project type<select value={form.kind} onChange={e=>update("kind",e.target.value)}><option>Development</option><option>Operations</option><option>Research</option><option>Infrastructure</option></select></label></div></fieldset>}
  {step===2&&<fieldset><legend>Purpose and outcomes</legend><p>Define why this project exists and how you will recognize success.</p><label>Primary objective<textarea required value={form.objective} onChange={e=>update("objective",e.target.value)} placeholder="What problem are we solving, and what outcome must the project deliver?"/></label><label>Success criteria<textarea value={form.success} onChange={e=>update("success",e.target.value)} placeholder="Measurable technical, schedule, or operational outcomes"/></label></fieldset>}
  {step===3&&<fieldset><legend>Initial plan</legend><p>These values establish the first schedule and budget baseline.</p><div><label>Start date<input type="date" required value={form.startDate} onChange={e=>update("startDate",e.target.value)}/></label><label>Target completion<input type="date" required min={form.startDate} value={form.endDate} onChange={e=>update("endDate",e.target.value)}/></label></div><label>Authorized budget (USD)<input type="number" min="0" step="1000" value={form.budget} onChange={e=>update("budget",e.target.value)} placeholder="0"/></label></fieldset>}
  {step===4&&<fieldset><legend>Review project charter</legend><p>Confirm the initial baseline. Every field can be refined after creation.</p><dl><div><dt>Project</dt><dd>{form.name} <small>{form.code.toUpperCase()}</small></dd></div><div><dt>Type</dt><dd>{form.kind}</dd></div><div><dt>Objective</dt><dd>{form.objective}</dd></div><div><dt>Schedule</dt><dd>{form.startDate} to {form.endDate}</dd></div><div><dt>Budget</dt><dd>{usd(Number(form.budget)||0)}</dd></div></dl></fieldset>}
  <footer>{step>1?<Button type="button" variant="outline" onClick={()=>setStep(s=>s-1)}>Back</Button>:<span/>}{step<4?<Button type="submit">Continue</Button>:<Button type="button" disabled={busy} onClick={()=>void create()}>{busy?"Creating project…":"Create project"}</Button>}</footer>
 </form></section></main>
}
const Head=({t,s}:{t:string;s:string})=><div className="phead"><h2>{t}</h2><p>{s}</p></div>;
function Portfolio({d,b,s,pick}:{d:D;b:number;s:number;pick:(p:P)=>void}){const avg=Math.round(d.projects.reduce((a,p)=>a+p.progress,0)/d.projects.length);return <><section className="stats"><Stat l="Active projects" v={String(d.projects.length)} s="Across development and operations" c="blue"/><Stat l="Portfolio progress" v={avg+"%"} s="Schedule completion" c="teal"/><Stat l="Budget used" v={Math.round(s/b*100)+"%"} s={usd(b-s)+" remaining"} c="gold"/><Stat l="Blocked tasks" v={String(d.tasks.filter(t=>t.status==="Blocked").length)} s={d.tasks.filter(t=>t.critical).length+" critical-path tasks"} c="red"/></section><div className="grid"><section className="panel"><Head t="Portfolio health" s="Select a project to drill down"/><div className="plist">{d.projects.map(p=><button key={p.id} onClick={()=>pick(p)}><i className={p.health}/><span><strong>{p.name}</strong><small>{p.code} · {p.status}</small></span><span><b>{p.progress}%</b><Progress value={p.progress}/></span><span><strong>{usd(p.spent)}</strong><small>of {usd(p.budget)}</small></span><em className={p.health}>{hl(p.health)}</em><ChevronRight/></button>)}</div></section><section className="panel"><Head t="Needs attention" s="Critical and blocked work"/><div className="attention">{d.tasks.filter(t=>t.critical).slice(0,4).map(t=><div key={t.id}><AlertTriangle/><span><strong>{t.title}</strong><small>Due {dt(t.due_date)} · {t.assignee}</small></span><em className={t.status==="Blocked"?"risk":"watch"}>{t.status}</em></div>)}</div></section></div><div className="grid lower"><section className="panel"><Head t="Critical path — next 30 days" s="Dependency-aware milestones"/><div className="timeline">{d.tasks.filter(t=>t.critical).map((t,i)=><div key={t.id}><b>{i+1}</b><span><strong>{t.title}</strong><small>{t.assignee} · {dt(t.due_date)}</small></span></div>)}</div></section><section className="panel"><Head t="Budget position" s="Committed spending by project"/>{d.projects.map(p=><div className="bar" key={p.id}><span><b>{p.code}</b><b>{Math.round(p.spent/p.budget*100)}%</b></span><Progress value={p.spent/p.budget*100}/></div>)}</section></div></>}
const Stat=({l,v,s,c}:{l:string;v:string;s:string;c:string})=><article className={"stat "+c}><span>{l}</span><strong>{v}</strong><small>{s}</small></article>;
function Projects({d,pick}:{d:D;pick:(p:P)=>void}){return <div className="cards">{d.projects.map(p=><button className="pcard" key={p.id} onClick={()=>pick(p)}><span><em className={p.health}>{hl(p.health)}</em><small>{p.code}</small></span><h2>{p.name}</h2><p>{p.objective}</p><Progress value={p.progress}/><small>{p.progress}% complete · {usd(p.budget-p.spent)} remaining</small></button>)}</div>}
function Schedule({d}:{d:D}){return <section className="panel"><Head t="Integrated schedule" s="Critical path highlighted in red"/><div className="gantt">{d.tasks.map((t,i)=><div key={t.id}><strong>{t.title}</strong><span><i className={t.critical?"critical":""} style={{left:(8+i*14)+"%"}}/></span><small>{dt(t.due_date)}</small></div>)}</div></section>}
function Tasks({d,q,reload}:{d:D;q:string;reload:()=>void}){const a=d.tasks.filter(t=>(t.title+t.assignee+t.status).toLowerCase().includes(q.toLowerCase()));const toggle=async(t:T)=>{await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"task-status",id:t.id,status:t.status==="Complete"?"Not started":"Complete"})});reload()};return <section className="panel"><Head t="Task register" s={a.length+" matching tasks"}/><div className="table"><div className="tr th"><span>Task</span><span>Project</span><span>Owner</span><span>Due</span><span>Status</span></div>{a.map(t=><button className="tr" key={t.id} onClick={()=>void toggle(t)}><span>{t.critical&&<i/>}{t.title}</span><span>{d.projects.find(p=>p.id===t.project_id)?.code}</span><span>{t.assignee}</span><span>{dt(t.due_date)}</span><em className={t.status==="Blocked"?"risk":""}>{t.status}</em></button>)}</div></section>}
function Budgets({d}:{d:D}){return <section className="panel"><Head t="Budget control" s="Current plan versus actual spending"/><div className="budgets">{d.projects.map(p=><div key={p.id}><span><strong>{p.name}</strong><b>{usd(p.spent)} / {usd(p.budget)}</b></span><Progress value={p.spent/p.budget*100}/><small>{usd(p.budget-p.spent)} available</small></div>)}</div></section>}
function Meetings({d}:{d:D}){return <section className="panel"><Head t="Meeting center" s="Agendas, decisions, and notes"/>{d.meetings.map(m=><article className="meeting" key={m.id}><b>{new Date(m.meeting_date).getUTCDate()}<small>SEP</small></b><div><small>{d.projects.find(p=>p.id===m.project_id)?.name}</small><h2>{m.title}</h2><p>{m.agenda}</p><Button variant="outline">Open agenda</Button></div></article>)}</section>}
function Metrics({d}:{d:D}){return <section className="panel"><Head t="Operational metrics" s="Latest performance against target"/><div className="metricgrid">{d.metrics.map(m=><div key={m.id}><Gauge/><small>{d.projects.find(p=>p.id===m.project_id)?.code}</small><strong>{m.value}{m.unit}</strong><span>Target {m.target}{m.unit}</span><Progress value={Math.min(100,m.value/m.target*100)}/></div>)}</div></section>}
function Reports({d}:{d:D}){return <section className="panel report"><Head t="Portfolio status report" s="Generated from current project records"/><div className="reporthead"><span><small>Reporting period</small><strong>September 2026</strong></span><Button onClick={()=>window.print()}><FileText/>Print / save PDF</Button></div><h2>Executive summary</h2><p>{d.projects.length} active programs are tracked. {d.projects.filter(p=>p.health==="good").length} are on track and {d.projects.filter(p=>p.health==="risk").length} require management attention. Spending is {usd(d.projects.reduce((s,p)=>s+p.spent,0))} against {usd(d.projects.reduce((s,p)=>s+p.budget,0))} authorized.</p><h2>Priority actions</h2><ul>{d.tasks.filter(t=>t.critical).map(t=><li key={t.id}>{t.title} — {t.status}, due {dt(t.due_date)}</li>)}</ul></section>}
function Drawer({p,tasks,close}:{p:P;tasks:T[];close:()=>void}){return <div className="overlay"><button onClick={close}/><aside className="drawer"><button className="close" onClick={close}><X/></button><em className={p.health}>{hl(p.health)}</em><small>{p.code}</small><h2>{p.name}</h2><p>{p.objective}</p><div className="kpis"><span><small>Progress</small><strong>{p.progress}%</strong></span><span><small>Budget remaining</small><strong>{usd(p.budget-p.spent)}</strong></span></div><h3>Open work</h3>{tasks.map(t=><div className="dtask" key={t.id}><ClipboardList/><span><strong>{t.title}</strong><small>{t.assignee} · {t.status}</small></span></div>)}</aside></div>}
function Add({projects,close,saved}:{projects:P[];close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({type:"task",title:f.get("title"),projectId:f.get("project"),assignee:f.get("assignee"),dueDate:f.get("due"),priority:f.get("priority"),critical:f.get("critical")==="on"})});saved()};return <div className="overlay modalwrap"><button onClick={close}/><form className="modal" onSubmit={submit}><button type="button" className="close" onClick={close}><X/></button><h2>Add task</h2><label>Task title<input name="title" required autoFocus/></label><label>Project<select name="project">{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div><label>Assignee<input name="assignee" required/></label><label>Due date<input type="date" name="due" required/></label></div><label>Priority<select name="priority"><option>High</option><option>Medium</option><option>Low</option></select></label><label className="check"><input type="checkbox" name="critical"/>Critical-path task</label><footer><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?"Saving…":"Add task"}</Button></footer></form></div>}
