"use client";
import {useEffect,useMemo,useState} from "react";
import {CalendarDays,Check,CheckCircle2,ChevronRight,Circle,FolderKanban,Menu,Pencil,Plus,Search,Users,X} from "lucide-react";
import {Button} from "@/components/ui/button";

type P={id:string;name:string;code:string;objective:string;status:string};
type T={id:string;project_id:string;title:string;assignee:string;due_date:string;status:string;priority:string;parent_id:string|null;notes:string};
type D={projects:P[];tasks:T[]};
type Sort="due"|"project"|"resource";

const today=()=>new Date().toISOString().slice(0,10);
const fmt=(date:string)=>new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(date+"T12:00:00Z"));
const post=(body:Record<string,unknown>)=>fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
const people=(value:string)=>value.split(/[,;]+/).map(v=>v.trim()).filter(Boolean);

export default function ProjectControl({displayName}:{displayName:string}){
 const[data,setData]=useState<D|null>(null),[project,setProject]=useState("all"),[sort,setSort]=useState<Sort>("due"),[query,setQuery]=useState(""),[mobile,setMobile]=useState(false),[edit,setEdit]=useState<{task?:T;parent?:T}|null>(null),[newProject,setNewProject]=useState(false);
 const load=()=>fetch("/api/workspace").then(r=>r.json()).then(setData);useEffect(()=>{void load()},[]);
 const tasks=useMemo(()=>{if(!data)return[];const open=data.tasks.filter(t=>t.status!=="Complete"&&(project==="all"||t.project_id===project)&&(t.title+" "+t.notes+" "+t.assignee).toLowerCase().includes(query.toLowerCase()));const projectName=(id:string)=>data.projects.find(p=>p.id===id)?.name||"";return open.sort((a,b)=>sort==="project"?projectName(a.project_id).localeCompare(projectName(b.project_id))||a.due_date.localeCompare(b.due_date):sort==="resource"?a.assignee.localeCompare(b.assignee)||a.due_date.localeCompare(b.due_date):a.due_date.localeCompare(b.due_date))},[data,project,sort,query]);
 if(!data)return <div className="loading"><b>TT</b><span>Loading task tracker…</span></div>;
 const selected=data.projects.find(p=>p.id===project),overdue=tasks.filter(t=>t.due_date<today()).length,dueSoon=tasks.filter(t=>t.due_date>=today()&&t.due_date<=new Date(Date.now()+7*86400000).toISOString().slice(0,10)).length;
 return <div className="tracker-shell">
  <aside className={mobile?"project-nav open":"project-nav"}>
   <div className="tracker-brand"><b><Check/></b><span><strong>Task Tracker</strong><small>{displayName}</small></span></div>
   <div className="nav-label"><span>Projects</span><button aria-label="Add project" onClick={()=>setNewProject(true)}><Plus/></button></div>
   <nav><button className={project==="all"?"active":""} onClick={()=>{setProject("all");setMobile(false)}}><FolderKanban/><span>All projects</span><small>{data.tasks.filter(t=>t.status!=="Complete").length}</small></button>{data.projects.map(p=><button key={p.id} className={project===p.id?"active":""} onClick={()=>{setProject(p.id);setMobile(false)}}><i>{p.code.slice(0,2)}</i><span>{p.name}</span><small>{data.tasks.filter(t=>t.project_id===p.id&&t.status!=="Complete").length}</small></button>)}</nav>
   <button className="new-project" onClick={()=>setNewProject(true)}><Plus/>New project</button>
  </aside>
  <main className="tracker-main">
   <header className="tracker-header"><button className="mobile-menu" onClick={()=>setMobile(v=>!v)}><Menu/></button><div><small>{selected?.code||"WORKSPACE"}</small><h1>{selected?.name||"Ongoing tasks"}</h1></div><Button onClick={()=>setEdit({})}><Plus/>Add task</Button></header>
   <div className="tracker-content">
    <section className="task-summary"><div><span>Open</span><strong>{tasks.length}</strong></div><div className={overdue?"danger":""}><span>Overdue</span><strong>{overdue}</strong></div><div><span>Due in 7 days</span><strong>{dueSoon}</strong></div><div><span>Resources</span><strong>{new Set(tasks.flatMap(t=>people(t.assignee))).size}</strong></div></section>
    <section className="task-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks, notes, or resources"/></label><label className="sort-control">Sort by<select value={sort} onChange={e=>setSort(e.target.value as Sort)}><option value="due">Due date</option><option value="project">Project</option><option value="resource">Resource</option></select></label></section>
    <section className="task-list"><div className="list-heading"><div><h2>{selected?selected.name:"All ongoing work"}</h2><p>{tasks.length} task{tasks.length===1?"":"s"} shown</p></div>{selected&&<span className="project-code">{selected.code}</span>}</div>
     {!tasks.length&&<div className="task-empty"><CheckCircle2/><h3>No ongoing tasks here</h3><p>Add a task or change the project filter.</p><Button onClick={()=>setEdit({})}><Plus/>Add task</Button></div>}
     {tasks.map(t=><TaskRow key={t.id} task={t} project={data.projects.find(p=>p.id===t.project_id)} parent={data.tasks.find(x=>x.id===t.parent_id)} complete={async()=>{await post({type:"task-status",id:t.id,status:"Complete"});void load()}} edit={()=>setEdit({task:t})} subtask={()=>setEdit({parent:t})}/>) }
    </section>
   </div>
  </main>
  {mobile&&<button className="tracker-scrim" onClick={()=>setMobile(false)}/>} {edit&&<TaskForm projects={data.projects} tasks={data.tasks} currentProject={project} task={edit.task} parent={edit.parent} close={()=>setEdit(null)} saved={()=>{setEdit(null);void load()}}/>}{newProject&&<ProjectForm projects={data.projects} close={()=>setNewProject(false)} saved={()=>{setNewProject(false);void load()}}/>}
 </div>
}

function TaskRow({task,project,parent,complete,edit,subtask}:{task:T;project?:P;parent?:T;complete:()=>void;edit:()=>void;subtask:()=>void}){const overdue=task.due_date<today();return <article className={"task-row "+(overdue?"overdue ":"")+(parent?"subtask":"")} onClick={edit}><button className="complete-task" aria-label="Mark complete" onClick={e=>{e.stopPropagation();void complete()}}><Circle/></button><div className="task-copy">{parent&&<small className="parent-label">Subtask of {parent.title}</small>}<h3>{task.title}</h3>{task.notes&&<p>{task.notes}</p>}<div className="task-meta"><span className="project-pill">{project?.code||"Project"}</span><span className={"status "+task.status.toLowerCase().replaceAll(" ","-")}>{task.status}</span>{people(task.assignee).map(person=><span className="resource" key={person}><Users/>{person}</span>)}</div></div><div className="task-due"><CalendarDays/><span><small>{overdue?"Overdue":"Due"}</small><strong>{fmt(task.due_date)}</strong></span></div><button className="add-subtask" onClick={e=>{e.stopPropagation();subtask()}}><Plus/>Subtask</button><ChevronRight className="row-chevron"/></article>}

function TaskForm({projects,tasks,currentProject,task,parent,close,saved}:{projects:P[];tasks:T[];currentProject:string;task?:T;parent?:T;close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false),defaultProject=task?.project_id||parent?.project_id||(currentProject==="all"?projects[0]?.id:currentProject);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:task?"task-update":"task",id:task?.id,projectId:f.get("project"),title:f.get("title"),assignee:f.get("resources"),dueDate:f.get("due"),status:f.get("status"),priority:"Medium",parentId:f.get("parent")||null,notes:f.get("notes")});saved()};return <Modal title={task?"Edit task":parent?"Add subtask":"Add task"} close={close} submit={submit} busy={busy}><label>Task name<input name="title" required autoFocus defaultValue={task?.title}/></label><div><label>Project<select name="project" defaultValue={defaultProject}>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Parent task<select name="parent" defaultValue={task?.parent_id||parent?.id||""}><option value="">None — top-level task</option>{tasks.filter(t=>t.id!==task?.id&&!t.parent_id).map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></label></div><div><label>Due date<input type="date" name="due" required defaultValue={task?.due_date||parent?.due_date||today()}/></label><label>Status<select name="status" defaultValue={task?.status||"Not started"}><option>Not started</option><option>In progress</option><option>Waiting</option><option>Blocked</option><option>Complete</option></select></label></div><label>Resources<input name="resources" required defaultValue={task?.assignee||parent?.assignee||""} placeholder="Names or teams, separated by commas"/></label><label>Notes<textarea name="notes" defaultValue={task?.notes||""} placeholder="Context, deliverables, decisions, or next steps"/></label></Modal>}

function ProjectForm({projects,close,saved}:{projects:P[];close:()=>void;saved:()=>void}){const[busy,setBusy]=useState(false);const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);await post({type:"project",name:f.get("name"),code:f.get("code"),objective:f.get("notes")||"",budget:0,startDate:today(),endDate:today(),draftId:""});saved()};return <Modal title="New project" close={close} submit={submit} busy={busy}><p className="modal-note">Projects organize tasks in the left menu. You can add as many as you need.</p><div><label>Project name<input name="name" required autoFocus/></label><label>Short code<input name="code" required maxLength={12}/></label></div><label>Project notes<textarea name="notes" placeholder="Optional purpose or scope"/></label>{projects.length>0&&<small className="existing-projects">Existing: {projects.map(p=>p.name).join(", ")}</small>}</Modal>}

function Modal({title,close,submit,busy,children}:{title:string;close:()=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean;children:React.ReactNode}){return <div className="task-modal-wrap"><button className="modal-backdrop" onClick={close}/><form className="task-modal" onSubmit={submit}><button type="button" className="modal-close" onClick={close}><X/></button><h2>{title}</h2>{children}<footer><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy}>{busy?"Saving…":"Save"}</Button></footer></form></div>}
